Slices and Strings comparisons
tact-lang/tact pull request #105
Opened 2023-11-30 13:15 UTC by Gusarich

This PR introduces the ability to compare both slices and strings via `==` operation.

For slice comparison, their hashes (calculated using `HASHSU`) can be compared directly.
As for strings, they are essentially slices and can be compared similarly. However, there's a consideration with strings due to their potential for various serializations (e.g., a string can be split in the middle and continued in a subsequent reference, still constituting a valid string). Upon reviewing the implementation of the `String` type in Tact, it was determined to be deterministic: all slices in a 'snake' representation are completely filled, except for the last one. Therefore, the same slice comparison method is applicable to strings as well.

2024-01-12 15:00 UTC, 0kenx commented
Hash is not the most gas efficient way to do this. There's a native opcode for this:

`int equal_slices(slice a, slice b) asm "SDEQ";`

2024-01-12 16:01 UTC, Skydev0h commented
> Hash is not the most gas efficient way to do this. There's a native opcode for this:
> 
> `int equal_slices(slice a, slice b) asm "SDEQ";`

SDEQ is, essentially, an abbreviation for Slice Data Equal. It does not account for refs at all. Use of hash covers both long (multi-cell) and short (single-cell) strings correctly.

2024-02-15 16:37 UTC, anton-trunov requested changes
Thanks for contributing more features 👍.
Would be great to
- have some runtime tests with `==` and `!=` both for strings and (some other kinds of) slices;
- add an entry to the changelog (to the `Changed` subsection).

2024-02-15 16:37 UTC, anton-trunov commented on src/generator/writers/writeExpression.ts
> +        // Case for strings equality
Looks like the case of strings is totally identical to the case of slices. If this is correct, I'd suggest to refactor the code avoiding duplication

2024-02-16 12:22 UTC, merged