Added Opcodes and Errors classes in generated Typescript code.
tact-lang/tact pull request #1100
Opened 2024-11-28 09:02 UTC by Shvandre

## Issue

Closes #1033 .

## Checklist

- [ ] I have updated CHANGELOG.md
- [ ] I have documented my contribution in `docs/` and made the build locally
- [ ] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-11-28 09:13 UTC, anton-trunov requested changes
let's either
- add tests with the new functionality, or
- simplify the existing tests using it

2024-11-28 13:45 UTC, anton-trunov commented
<img width="334" alt="image" src="https://github.com/user-attachments/assets/995d0aad-02d3-4a81-a8be-a2f9521c16ea">

apparently this is not entirely true :)
CI is red because Prettier is unhappy

2024-11-28 13:53 UTC, verytactical commented on src/bindings/writeTypescript.ts
> +    w.append("export abstract class Opcodes {");
TypeScript has `enum` syntax for this. `abstract class` implies user should inherit from it to get access to its fields, and that's definitely not the way in a language without multiple inheritance.

2024-11-28 13:54 UTC, verytactical commented on src/bindings/writeTypescript.ts
> +                    `this: new (address: Address, init?: { code: Cell, data: Cell }) => T,` +
This kind of types is meant to type legacy JS code, not to write or generate novel code.

2024-11-28 13:55 UTC, verytactical commented on src/bindings/writeTypescript.ts
> +            Object.entries(abi.errors).forEach(([k, abiError]) => {
`for (const [k, abiError] of abi.errors)` would be more readable, concise and performant.

2024-11-28 13:56 UTC, verytactical commented on src/bindings/writeTypescript.ts
> +                w.append(`    "${escapedMessage}": ${k},`);
This is an indent that doesn't take `.inIndent()` state in consideration.

2024-11-28 14:22 UTC, anton-trunov commented on src/bindings/writeTypescript.ts
> +            Object.entries(abi.errors).forEach(([k, abiError]) => {
@verytactical there is a few of instances of `Object.entries(foo).forEach(([k, v]) ...` in the codebase. Could you please open an issue to refactor those?

2024-12-04 11:27 UTC, anton-trunov commented
Let's move on with this PR please. @Shvandre can we see some tests for the changes?

2024-12-11 12:05 UTC, Shvandre commented
Decided, to put this into the backlog. Will return to this after Typescript codegen refactoring

2024-12-11 12:05 UTC, closed without merging