feat: clarify error message for bounced types from which accessed a field that does not fit in 224 bytes
tact-lang/tact pull request #1111
Opened 2024-12-03 17:11 UTC by i582

Previously, the following code would produce a confusing error:

```
message Withdraw {
    data: Int as uint128;
    amount: Int as uint128;
}

contract Fund {
    balance: Int as uint256 = 0;

    bounced(msg: bounced<Withdraw>){
        self.balance += msg.data;
        self.balance += msg.amount; // Type bounced<"Withdraw"> does not have a field named "amount"
    }
}
```

Now, it gives following error:

> Maximum size of the bounced message is 224 bytes, but the "amount" field cannot fit into it due to the size of previous fields or its own size, so it cannot be accessed. Make the type of the fields before this one smaller, or reduce the type of this field so that it fits into 224 bytes

If the type specifies only one field, it will look like this:

> Maximum size of the bounced message is 224 bytes, but the "amount" field cannot fit into it because its too big, so it cannot be accessed. Reduce the type of this field so that it fits into 224 bytes

It's way too big, but since we don't have a more complex UI for errors (like in Rust), a long clear message with all the details is better than a short but not very clear message.

## Issue

Closes #1021.

## Checklist

- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-12-04 11:26 UTC, anton-trunov requested changes
Looks good, just some minor remarks

2024-12-04 11:26 UTC, anton-trunov commented on src/types/resolveExpression.ts
> +                if (srcT.fields.length == 1) {
```suggestion
                if (srcT.fields.length === 1) {
```

2024-12-04 11:26 UTC, anton-trunov commented on src/types/resolveExpression.ts
I would argue 

```ts
if (src.kind === "ref_bounced") {
        fields = fields.slice(0, srcT.partialFieldCount);
}
```

needs to be changed: let's not remove the fields here and just check that for bounced messages if the field's index is beyond `srcT.partialFieldCount` then we should make the message more informative.

2024-12-04 11:31 UTC, i582 commented on src/types/resolveExpression.ts
Makes sense, I thought about it, but decided to make the change as small as possible

2024-12-04 11:47 UTC, i582 commented on src/types/resolveExpression.ts
Done

2024-12-04 11:47 UTC, i582 commented on src/types/resolveExpression.ts
> +                if (srcT.fields.length == 1) {
Done

2024-12-04 11:55 UTC, i582 commented on src/types/resolveExpression.ts
> +                if (srcT.fields.length == 1) {
I'm not sure if we need to include info about indexes, it would make the message more confusing to me

2024-12-04 11:58 UTC, i582 commented
Kinda strange failure on CI:
```
Tact compilation failed
Error: stdlib/std/base.tact:23:13: Invalid type "Cell" for binary operator ">"
Line 23, col 13:
  22 |         // Lock storage if needed
> 23 |         if (self.storageReserve > 0) { // Optimized in compile-time
                   ^~~~~~~~~~~~~~~~~~~~~~~
  24 |             let ctx: Context = context();
```

2024-12-05 10:16 UTC, anton-trunov approved these changes

2024-12-05 10:17 UTC, merged