feat: `fromCell` method for maps
tact-lang/tact pull request #1271
Opened 2024-12-29 00:44 UTC by Gusarich

## Issue

Closes #1229.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have documented my contribution in `docs/` and made the build locally
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-12-29 08:56 UTC, anton-trunov requested changes
1. Let's change the syntax here to make it consistent with `fromCell` for structs/messages.

2. We need negative tests showing what happens when the cell does not represent a valid map. We need to validate the cell and it seems to me we could use TVM's `LDDICTS` instruction here and check the remainder is an empty slice. Or is there a better approach? What do you think?

2024-12-29 08:56 UTC, anton-trunov commented on docs/src/content/docs/book/maps.mdx
> +fizz.fromCell(cell);
hmmm, this should be consistent with what we have for structs:

```tact
struct Fizz { foo: Int }
let fizzCell = ...
let parsedFizz: Fizz = Fizz.fromCell(fizzCell);
```

So I would expect something like:

```tact
let fizz = map<Int, Int>.fromCell(cell);
```

This makes parsing harder but it seems it's too late to do it differently

2024-12-29 09:01 UTC, Gusarich commented
> 2\. We need negative tests showing what happens when the cell does not represent a valid map. We need to validate the cell and it seems to me we could use TVM's `LDDICTS` instruction here and check the remainder is an empty slice. Or is there a better approach? What do you think?

@anton-trunov `LDDICTS` doesn't check anything, and there are no TVM instructions for checking the whole dictionary for "correctness" actually.

2024-12-29 09:04 UTC, anton-trunov commented
@Gusarich The TVM docs say this for `LDDICSTS`: 

> Loads (parses) a (Slice-represented) dictionary s' from Slice s, and returns the remainder of s as s''

So, if a cell is map, then the remainder should be an empty slice, if I understand this correctly.

2024-12-29 09:13 UTC, Gusarich commented
> So, if a cell is map, then the remainder should be an empty slice, if I understand this correctly.
@anton-trunov `LDDICTS` doesn't even check the header of the map, it just checks the one single bit indicating whether it's empty or not when it's represented as `Maybe X` (similarly to what `.load_dict()` does.

https://github.com/ton-blockchain/ton/blob/ea0dc161639ef2640876d6de06f7224ac5873847/crypto/vm/dictops.cpp#L121-L146

2025-01-26 06:38 UTC, closed without merging

2025-01-26 06:38 UTC, anton-trunov commented
Let's close this for now, we need to brainstorm how this feature should look like in the end