feat(docs): variable integer serialization types
tact-lang/tact pull request #1274
Opened 2024-12-30 22:53 UTC by novusnota

Slowly getting back in the saddle.

## Issue

Closes #1252.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-12-31 07:27 UTC, anton-trunov requested changes

2024-12-31 07:27 UTC, anton-trunov commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
This needs to be merged with the `coins` description, since it's just an alias to `varuint16`

2025-01-01 12:28 UTC, anton-trunov commented
The map page should also mention which annotations are supported for key and value types:

> Since TVM natively supports only maps with fixed-width keys, you can only use the `uint` and `int` serialization annotations for map keys...

2025-01-03 09:11 UTC, novusnota commented
> The map page should also mention which annotations are supported for key and value types

Got it

2025-01-14 11:42 UTC, anton-trunov commented
@novusnota ping

2025-01-19 15:49 UTC, novusnota commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
Currently having troubles merging those descriptions. `coins` were there for a long time, so it's only natural to make other `varuint` formats reference and base their descriptions on it.

That said, I'll try to think of some other approaches.

P.S.: However, resolved the suggestions regarding maps: they now have an explicit description of what serialization formats can be used and when

2025-01-19 19:13 UTC, anton-trunov commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
> P.S.: Resolved the suggestions regarding maps: described which serialization formats can be used and when

I cannot see those changes. Did you forget to push them?

2025-01-19 19:35 UTC, novusnota commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
> I cannot see those changes. Did you forget to push them?

Yup, pushed now

2025-01-19 19:40 UTC, anton-trunov commented on docs/src/content/docs/book/maps.mdx
> +No other [allowed key or value types](#allowed-types) besides [`Int{:tact}`][int] have serialization formats available.
there is also `bytes32` and `bytes64`, and `as remaining` can also be considered a serialization format

2025-01-19 19:52 UTC, novusnota commented on docs/src/content/docs/book/maps.mdx
> +No other [allowed key or value types](#allowed-types) besides [`Int{:tact}`][int] have serialization formats available.
Bytes32 and bytes64 are only defined for Slice, which isn't a value type.
And we've banned use of `remaining` in maps afair.

2025-01-22 23:15 UTC, novusnota commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
@anton-trunov can you please state your idea again? I do not understand the intent — things on the page seem fine as they are for me

2025-01-23 13:02 UTC, novusnota commented on docs/src/content/docs/book/integers.mdx
> +### Variable integer types {#serialization-varint}
Solved

2025-01-23 14:43 UTC, anton-trunov approved these changes

2025-01-23 14:44 UTC, merged