chore: format codebase with Prettier
tact-lang/tact pull request #227
Opened 2024-04-02 20:39 UTC by anton-trunov

and introduce a CI check that the codebase is properly formatted

Closes #226

* [x] I have updated CHANGELOG.md
* [x] I have added unit tests to demonstrate the contribution is correctly implemented
* [x] I have run all the tests locally and no test failure was reported
* [x] I did not introduce unrelated formatting/whitespace changes in the code base
* [x] I did not do unrelated and/or undiscussed refactorings

Everything is the default, except I kept the 4 spaces indentation level for TS and JS files (see `.editorconfig`) and excluded the auto-generated and vendored files that are not in `.gitignore`, which Prettier ignores as well (see `.prettierignore`).

2024-04-02 21:10 UTC, novusnota requested changes

2024-04-02 21:10 UTC, novusnota commented on .prettierignore
Here it's better to prepend all those paths with `/` to ensure that Prettier ignores only those and not any relative `grammar/` folders, for example.

2024-04-02 21:13 UTC, anton-trunov commented on .prettierignore
should be fixed now

2024-04-02 21:17 UTC, novusnota commented on .prettierignore
I meant the following:

```gitignore
/dist

/src/func/funcfiftlib.js
/src/func/funcfiftlib.wasm.js
/src/grammar/grammar.ohm-bundle.d.ts
/src/grammar/grammar.ohm-bundle.js
/src/imports/stdlib.ts
/grammar
````

2024-04-02 22:48 UTC, byakuren-hijiri submitted a review, later dismissed
I like the idea of unified code formatting, and the default configuration suggested by Prettier looks good to me.

I would suggest only removing the following line from the`pull_request_template.md`, as it is checked by CI for now:

>  I did not introduce unrelated formatting/whitespace changes in the code base

2024-04-03 07:25 UTC, anton-trunov commented on .prettierignore
thanks, never learnt that actually before now :)

2024-04-03 07:26 UTC, anton-trunov commented
@byakuren-hijiri thanks! [if only there was a way to automatically check all the other bullet points, lol]

2024-04-03 08:26 UTC, novusnota approved these changes
Neat!
"Live and learn ~~and break CI~~" :)

2024-04-03 09:44 UTC, merged