Constant evaluation of `newAddress`
tact-lang/tact pull request #237
Opened 2024-04-10 10:00 UTC by Gusarich

Closes #214 

- [ ] I have updated CHANGELOG.md
- [x] I have added unit tests to demonstrate the contribution is correctly implemented
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

also covered constants with test. for some reason there were no checks for their values.

2024-04-11 08:32 UTC, anton-trunov requested changes

2024-04-11 08:32 UTC, anton-trunov commented on src/types/resolveConstantValue.ts
> +                if (!enabledMasterchain(ctx)) {
We are not checking the workchain is either `-1` or `0` like in the code above. Why is that?

2024-04-11 08:32 UTC, anton-trunov commented on src/types/resolveConstantValue.ts
> +        } else if (ast.name === "newAddress") {
The first and second arguments are not necessarily literals, those can be constant expressions too, so we need to recursively process them. (Even if we don't do it elsewhere)

2024-04-17 10:16 UTC, Gusarich commented on src/types/resolveConstantValue.ts
> +        } else if (ast.name === "newAddress") {
> The first and second arguments are not necessarily literals, those can be constant expressions too, so we need to recursively process them. (Even if we don't do it elsewhere)

but that actually happens on the next lines in the code. `reduceInt(ast.args[0])` and `reduceInt(ast.args[1])`.

2024-04-17 10:22 UTC, anton-trunov commented on src/types/resolveConstantValue.ts
> +        } else if (ast.name === "newAddress") {
you are right, I misread the code, sorry

2024-04-17 10:23 UTC, anton-trunov approved these changes
LGTM

2024-04-17 10:28 UTC, merged