Allow underscores as unused variable identifiers
tact-lang/tact pull request #338
Opened 2024-05-15 13:57 UTC by Gusarich

Closes #319 

- [ ] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

2024-06-09 01:36 UTC, anton-trunov requested changes
Let's fix the merge conflicts here

2024-06-09 12:31 UTC, novusnota commented
As of now, it only works for `foreach` and `catch`, right?

2024-06-10 05:47 UTC, Gusarich commented
> As of now, it only works for `foreach` and `catch`, right?

Are there any other cases where we need it?

2024-06-10 05:56 UTC, novusnota commented
> Are there any other cases where we need it?
I don't think so, at least now. When we'll have #298 in the future, identifiers in `let` declarations would them though.

2024-06-10 06:13 UTC, anton-trunov commented
> When we'll have https://github.com/tact-lang/tact/issues/298 in the future, identifiers in let declarations would need them though.

Actually, `let`-statements should have underscores even now. This can be used as a clear indication that some functions gets called not for its return value but for its side-effects:

```
let _ : Foo = effectfulFun(x, y, z);
```

When we have a bit of type inference, the snippet above will become

```
let _ = effectfulFun(x, y, z);
```

In this case a static analyzer won't complain about unused values, whereas it should issue a warning for 

```
effectfulFun(x, y, z);
```

if `effectfulFun` is a non-void function.

2024-06-11 10:00 UTC, Gusarich commented
Added support for let-statements and also resolved all merge conflicts

2024-06-12 07:19 UTC, Gusarich commented
resolved merge conflicts

2024-06-14 07:21 UTC, Gusarich commented
@anton-trunov resolved merge conflicts yet again after merge of #198

2024-06-14 08:25 UTC, anton-trunov requested changes
Almost there!

2024-06-14 08:25 UTC, anton-trunov commented on src/types/stmts/var-underscore-name-in-let.tact
> +    let _: Int = someImpureFunction();
Let's also add a test with `let` and no type annotation:
```
    let _ = someImpureFunction();
```

2024-06-14 08:25 UTC, anton-trunov commented on src/types/__snapshots__/resolveStatements.spec.ts.snap
> +"<unknown>:7:14: Unable to resolve id _
I would expect this error message to be

> Variable name cannot be '_'

or, if we converge on the proposed change below:

> Wildcard variable name '_' cannot be used

2024-06-14 08:25 UTC, anton-trunov commented on src/types/resolveStatements.ts
> +        throw Error("Variable name cannot be '_'");
```suggestion
        throw Error("Wildcard variable name '_' cannot be used");
```

2024-06-14 08:25 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/underscore-variable.tact
> +        let _: Int = self.increaseSomething();
```suggestion
        let _ = self.increaseSomething();
        let _ = self.increaseSomething();
```

2024-06-14 08:25 UTC, anton-trunov commented on src/types/resolveStatements.ts
> +                    sctx = addVariable(s.name, variableType, sctx);
we should probably move the check `s.name !== "_"` inside `addVariable` itself -- it would just ignore it

2024-06-14 08:25 UTC, anton-trunov commented on src/types/resolveStatements.ts
> +                }
Let's refactor this code into a helper function and reuse it in this file in numerous places.

2024-06-14 09:38 UTC, Gusarich commented
@anton-trunov resolved everything

2024-06-14 18:17 UTC, anton-trunov approved these changes

2024-06-14 18:17 UTC, merged