feat: add support for |= &= and ^=
tact-lang/tact pull request #350
Opened 2024-05-22 22:02 UTC by Alejandbel

Closes #328

- [ ] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

2024-05-23 06:42 UTC, Gusarich submitted a review, later dismissed
LGTM, great job! Also thanks for removing these whitespaces from `grammar.ohm`, they were pissing me off, haha 😆

2024-05-23 14:09 UTC, byakuren-hijiri commented
We should consider modifying the type checker for this case, as these operations should be applied only to numeric types: https://github.com/tact-lang/tact/issues/353.

2024-05-24 06:02 UTC, Gusarich commented
> We should consider modifying the type checker for this case, as these operations should be applied only to numeric types: #353.

@Alejandbel you don't have to change anything in your PR for that, I've resolved this in #356

2024-05-24 08:24 UTC, anton-trunov requested changes
Thanks! I left some minor comments. Btw, we can only merge this PR after Tact v1.3.1 is released. In the mean we will inevitably introduce some merge conflicts.

2024-05-24 08:24 UTC, anton-trunov commented on CHANGELOG.md
> +- Extend assign operators with `|=`, `&=`, `^=`: PR [#350](https://github.com/tact-lang/tact/pull/350)
```suggestion
- Extend augmented assignment operators with bitwise `|=`, `&=`, `^=`: PR [#350](https://github.com/tact-lang/tact/pull/350)
```

2024-05-24 08:24 UTC, anton-trunov commented on src/grammar/grammar.ohm
The conflicts from the whitespace changes will be a pain in the neck to resolve after the upcoming PR fixing issue #341. So, let's please remove the unrelated changes from this file

2024-05-24 08:24 UTC, anton-trunov commented on src/grammar/grammar.ohm
> +                             | StatementAugmentedAssignXor
These identifiers should have `Bitwise` in them for consistency with the rest of the grammar

2024-05-28 13:51 UTC, anton-trunov commented
@Alejandbel Could you please update your PR after the grammar refactoring PR #365?

2024-05-31 10:37 UTC, Alejandbel commented
> @Alejandbel Could you please update your PR after the grammar refactoring PR #365?

Yep, sure, will update it today

2024-06-02 09:38 UTC, Alejandbel commented
> @Alejandbel Could you please update your PR after the grammar refactoring PR #365?

Updated

2024-06-02 09:57 UTC, anton-trunov submitted a review, later dismissed
Perfect! Thanks a lot!

2024-06-04 04:43 UTC, anton-trunov commented
Hey @Alejandbel, your contribution qualifies for the Tact contributor [SBT](https://society.ton.org/contribute-to-tact-compiler), would you mind sharing your TON wallet?

2024-06-04 13:32 UTC, Alejandbel commented
Sure, UQBSzBN6cnxDwDjn_IQXqgU8OJXUMcol9pxyL-yLkpKzYpKR

> Hey @Alejandbel, your contribution qualifies for the Tact contributor [SBT](https://society.ton.org/contribute-to-tact-compiler), would you mind sharing your TON wallet?

2024-06-05 14:52 UTC, anton-trunov commented
SBT sent!

2024-06-08 09:17 UTC, anton-trunov approved these changes

2024-06-08 09:48 UTC, merged