feat: add test case covering recursive functions
tact-lang/tact pull request #359
Opened 2024-05-24 19:46 UTC by vitorpy

Closes #303

- [ ] I have updated CHANGELOG.md
- [X] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [X] I have run all the tests locally and no test failure was reported
- [X] I did not do unrelated and/or undiscussed refactorings

2024-05-25 08:45 UTC, anton-trunov commented on src/types/stmts/case-22.tact
I think it would be better to create a "feature" test case: those are both type-checked and we can do dynamic testing with those. Something similar to https://github.com/tact-lang/tact/blob/main/src/test/feature-math.spec.ts

2024-05-25 08:45 UTC, anton-trunov commented on src/types/stmts/case-22.tact
It could be named like `feature-recursion`

2024-05-26 13:13 UTC, Gusarich requested changes
let's also add a recursive function outside of the contract (not a get-method) and call it in a separate function

2024-05-27 07:20 UTC, Gusarich submitted a review, later dismissed
LGTM

2024-05-27 07:50 UTC, anton-trunov reviewed
LGTM too, just a nitpick in the changelog

2024-05-27 07:50 UTC, anton-trunov commented on CHANGELOG.md
> +- Unit tests for recursive functions: PR [#359](https://github.com/tact-lang/tact/pull/359)
These are end-to-end tests, I'd say

2024-05-27 09:40 UTC, anton-trunov commented on CHANGELOG.md
> +- Unit tests for recursive functions: PR [#359](https://github.com/tact-lang/tact/pull/359)
```suggestion
- Tests for recursive functions: PR [#359](https://github.com/tact-lang/tact/pull/359)
```

2024-05-27 09:40 UTC, anton-trunov approved these changes

2024-05-27 09:54 UTC, merged