Implement `fromCell` and `fromSlice` methods for structs
tact-lang/tact pull request #418
Opened 2024-06-14 09:17 UTC by Gusarich

Closes #344 

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-06-14 09:45 UTC, Gusarich commented
Just realised that I didn't add any negative tests for struct parsing

2024-06-16 08:31 UTC, anton-trunov requested changes
We need some tests to make sure the following works as expected.
First, the user defines a `fromCell`:

```
extends mutates fun fromCell(self: Cell, _: Cell): MyStruct1 {
  return MyStruct1 { ... };
}
```

And now the user is trying to do something weird:
```
contract StructsTester {
    receive() { }

    get fun fromCell1(src: Cell): MyStruct1 {
        let MyStruct1: Cell = beginCell().endCell();  // it's a cell here!
        let s: MyStruct1 = MyStruct1.fromCell(src);
        return s;
    }
}
```

What do you expect to happen in this case?

2024-06-16 09:07 UTC, Gusarich commented
@anton-trunov do you mean a user-defined function with the same name - `fromCell` or `fromSlice`?

I think it should work the same way as it works for all other built-ins such as `toCell` for structs, and `set`, `get` and `del` for maps.

2024-06-16 09:09 UTC, anton-trunov commented
@Gusarich Yep. Because right now this shadowing is allowed and it overrides the generated code.

2024-06-16 09:53 UTC, Gusarich commented
> @Gusarich Yep. Because right now this shadowing is allowed and it overrides the generated code.

Should we forbid such shadowing for all built-in functions?

2024-06-16 10:28 UTC, anton-trunov commented
Yeah, we do not allow any form of shadowing in Tact. And if we do, it's a bug

2024-06-16 10:28 UTC, anton-trunov commented
btw, there is some merge conflicts

2024-06-16 12:07 UTC, Gusarich commented
> Yeah, we do not allow any form of shadowing in Tact. And if we do, it's a bug

In this case maybe we should create a separate issue about that and resolve that in another PR?

2024-06-16 14:04 UTC, anton-trunov commented
> In this case maybe we should create a separate issue about that and resolve that in another PR?

Yeah, there are issues like that, for instance #307. There is a special tag for those https://github.com/tact-lang/tact/labels/scope%3A%20var-scope

2024-06-18 14:52 UTC, anton-trunov requested changes
LGTM! Just some minor tweaks in the suggested changes

2024-06-18 14:52 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/structs.tact
> +        let s: MyStruct1 = MyStruct1.fromCell(src);
```suggestion
        let s = MyStruct1.fromCell(src);
```

2024-06-18 14:52 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/structs.tact
> +        return s;
```suggestion
        return MyStruct1.fromSlice(src);
```

2024-06-18 14:52 UTC, anton-trunov commented on src/types/resolveExpression.ts
> +                // Handle struct calls
```suggestion
                // Handle static struct method calls
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromCell() is implemented only a struct type",
```suggestion
                        "fromCell() is implemented only for struct types",
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromCell() is implemented only a struct type",
```suggestion
                        "fromCell() is implemented only for struct types",
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromCell() is implemented only a struct type",
```suggestion
                        "fromCell() is implemented only for struct types",
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromSlice() is implemented only a struct type",
```suggestion
                        "fromSlice() is implemented only for struct types",
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromSlice() is implemented only a struct type",
```suggestion
                        "fromSlice() is implemented only for struct types",
```

2024-06-18 14:52 UTC, anton-trunov commented on src/abi/struct.ts
> +                        "fromSlice() is implemented only a struct type",
```suggestion
                        "fromSlice() is implemented only for struct types",
```

2024-06-19 04:41 UTC, anton-trunov approved these changes

2024-06-19 04:42 UTC, merged