fix: improve `funcId` recognition and squash misdetection bugs
tact-lang/tact pull request #636
Opened 2024-07-28 01:22 UTC by novusnota

That took a looooooooot of RegEx iterations, including going into `grammar.ts` and trying to adjust things in the semantic analysis. Fortunately, that wasn't needed.

Closes #635

- [ ] I have updated CHANGELOG.md
~~- [ ] I have documented my contribution in Tact Docs: https://github.com/tact-lang/tact-docs/pull/PR-NUMBER~~
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-07-28 08:18 UTC, anton-trunov requested changes

2024-07-28 08:18 UTC, anton-trunov commented on CHANGELOG.md
> +- FunC function identifiers with characters from hexadecimal set: PR [#635](https://github.com/tact-lang/tact/pull/635)
```suggestion
- FunC function identifiers with characters from hexadecimal set: PR [#636](https://github.com/tact-lang/tact/pull/636)
```

2024-07-28 08:18 UTC, anton-trunov commented on src/grammar/test/items-native-fun-funcid.tact
> +// There is a only small set of cases related to the above that our parser won't parse, but C++ FunC's will:
looks like this note should go to grammar.ohm

2024-07-28 08:21 UTC, anton-trunov commented
To be on the safe side, let's take `stdlib.fc` and `mathlib.fc` as libraries that are commonly used and see if we can add more function identifiers from those libs into our positive tests to make sure people will be able to FFI with those.

2024-07-28 09:36 UTC, anton-trunov commented on src/grammar/grammar.ohm
> +
```suggestion
      NOTE(novusnota):

```

2024-07-28 09:37 UTC, anton-trunov commented on src/grammar/grammar.ohm
> +
Let's remove this part, there is commit history to query authorship and additional context

2024-07-28 17:03 UTC, anton-trunov requested changes
This PR accepts, for instance, `+` as a valid FunC identifier, but it's actually not.

Something like this should work:
```
    funcInvalidId = "_" ")" --notUnderscore
                  | ("+" | "-" | "*" | "/" | "~/" | "^/" | "%" | "~%" | "^%" | "/%") ")" --notArithOperator
      // more operators here
                  | ("-"? digit+) ")" --notDecimalNumber
                  | ("-"? "0x" hexDigit+) ")" --notHexadecimalNumber
    funcPlainId = ~funcInvalidId (~(whiteSpace | "(" | ")" | "," | "." | ";" | "~") any)+
```

2024-07-28 17:12 UTC, novusnota commented
Nice observation! I'd try putting lookaheads `&` in front of those ")" so they don't get parsed, but let me try your suggestion first :)

2024-07-28 20:37 UTC, novusnota commented
Possibly, I've found a cleaner solution, which doesn't require the ")" and can be used in the FunC parser too (the current one fails there in presence of ")" and stuff).

![image](https://github.com/user-attachments/assets/6fe47d83-52e3-442b-a70b-504a7deb14a2)

It passes similar set of tests we have for function identifiers, but adapted to FunC code:

![image](https://github.com/user-attachments/assets/61e7a1f9-487a-4996-8764-c994b05dbee5)

2024-07-30 05:44 UTC, anton-trunov commented
@novusnota So, what's the current status of this PR?

2024-07-30 11:49 UTC, novusnota commented
@anton-trunov It's a working and robust solution. The alternative would be to do invalidation of identifiers during semantic analysis, which enhances the error messages further, but that seems to be a bit out of scope of this PR. Wdyt?

2024-07-30 14:01 UTC, anton-trunov approved these changes

2024-07-30 14:01 UTC, merged