feat: testing for repeat ranges
tact-lang/tact pull request #766
Opened 2024-08-28 23:14 UTC by novusnota

## Issue

Closes #654.

## Checklist

- [ ] I have updated CHANGELOG.md
- [ ] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-08-28 23:16 UTC, novusnota commented
Stumble across the exit code 37 in the action phase (which is "not enough Toncoins") no matter how big I make the treasure to be. @Gusarich, could you please check?

2024-08-29 03:42 UTC, anton-trunov requested changes

2024-08-29 03:42 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/repeat-range.tact
> +        } catch (_) { caseCounter += 1 }
Let's check we get a specific exit code here, it's not immediately obvious what `caseCounter += 1` means here.

2024-08-29 03:42 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/repeat-range.tact
I would say we either group all exit code test into a separate directory or rename this file into `repeat.tact` and put all `repeat`-loop related tests in it.

2024-08-29 03:42 UTC, anton-trunov commented on src/test/e2e-emulated/contracts/repeat-range.tact
> +        return counter; // 0, if things go right
How about we compare with `0` internally and just return a boolean? Sandbox tests can be made more uniform this way

2024-08-29 04:02 UTC, anton-trunov commented
> Stumble across the exit code 37 in the action phase (which is "not enough Toncoins") no matter how big I make the treasure to be

@novusnota There is a maximal gas limit for processing one message,  it should 0.4 TON atm: https://github.com/tact-lang/tact-docs/pull/298#issuecomment-2207412040. I haven't checked if Sandbox respects this limit, but it should be configurable (although we actually shouldn't increase it)

2024-08-29 08:24 UTC, novusnota commented on src/test/e2e-emulated/contracts/repeat-range.tact
A separate directory seems a better option since `repeat` is also used in testing const-eval, for example

2024-09-05 13:35 UTC, anton-trunov approved these changes

2024-09-05 13:35 UTC, merged