feat: enhance `asm` functions to support all of the Fift-asm syntax
tact-lang/tact pull request #855
Opened 2024-09-20 03:45 UTC by novusnota

Note, that while it's possible to support the syntax via Ohm without constucting ASTs, it's impossible to support the AST generation without outsourcing that part of the parser to the recursive-descent one, which would also keep track of dictionary of words/instructions and the TVM stack, at least approximating it. [See this for more info](https://github.com/tact-lang/tact/issues/837#issuecomment-2362498612).

## Issue

Closes #837.

## Checklist

- [ ] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-09-23 08:09 UTC, anton-trunov requested changes
Wait, this PR definitely does not close the linked issue as there is no AST model of `asm`-instructions.

2024-09-23 08:09 UTC, anton-trunov commented on src/grammar/grammar.ohm
> +    // A chuck of non-whitespace characters forms a word in Fift
```suggestion
    // A chunk of non-whitespace characters forms a word in Fift
```

2024-09-23 11:19 UTC, novusnota commented
Changed the linked issue to #857. I'm willing to return to #837 later, preferably when we start moving to Tact 2.0 and a new parser for it. Alternatively, can tackle it after other remaining issues on 1.6.0 milestone for me to resolve (both here and for docs)

2024-09-23 19:48 UTC, anton-trunov requested changes
We should definitely add more positive tests from some known Fift-projects.

Can we parse at least some part of `Asm.fif`? 

Some examples can be taken from this list: https://docs.ton.org/develop/smart-contracts/examples#fift-smart-contracts and this list: https://github.com/ton-blockchain/ton/tree/master/crypto/smartcont.

2024-09-23 22:59 UTC, novusnota commented
@anton-trunov added Fift library to the test suite and made sure that we don't create unnecessary snapshots for them

2024-09-24 05:52 UTC, anton-trunov approved these changes
Amazing job!

2024-09-24 05:52 UTC, merged