fix: `as coins` map value serialization type now generates correct typescript binding
tact-lang/tact pull request #987
Opened 2024-10-25 05:47 UTC by Gusarich

## Issue

Closes #985.

## Checklist

- [x] I have updated CHANGELOG.md
- [ ] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

2024-10-25 05:47 UTC, Gusarich commented
will add tests in a moment

2024-10-25 06:00 UTC, anton-trunov commented
What about the FunC part, shouldn't it use `load_coins` in this case?

2024-10-25 07:09 UTC, Gusarich commented
> What about the FunC part, shouldn't it use `load_coins` in this case?

It does

2024-10-25 07:14 UTC, Gusarich commented
> What about the FunC part, shouldn't it use `load_coins` in this case?

at first I thought that the FunC part works fine already, but just looked through the generated code for `as coins` maps and turned out that it's completely wrong and just uses 257-bit long integers. I will fix that too

2024-10-25 07:16 UTC, Gusarich commented
but it'll be easier to fix after #941 gets merged

2024-11-02 06:51 UTC, anton-trunov requested changes
Awesome stuff! Just minor comments

2024-11-02 06:51 UTC, anton-trunov commented on CHANGELOG.md
> +- `as coins` map value serialization type is now handled correctly: PR [#987](https://github.com/tact-lang/tact/pull/987)
Let's move it to Fixed

2024-11-02 06:51 UTC, anton-trunov commented on src/generator/writers/writeStdlib.ts
> +    const signatureRetType =
Looks like this should be refactored into a helper function (I should have done it in my previous refactoring)

2024-11-02 07:30 UTC, anton-trunov approved these changes

2024-11-05 09:04 UTC, merged