refactor: add utility to err on unreachable branches
tact-lang/tact pull request #991
Opened 2024-10-28 14:45 UTC by verytactical

## Issue

Closes #915.

## Checklist

- [ ] I have updated CHANGELOG.md
- [ ] I have run all the tests locally and no test failure was reported
- [ ] I have run the linter, formatter and spellchecker
- [ ] I did not do unrelated and/or undiscussed refactorings

2024-10-29 13:12 UTC, anton-trunov commented
It would be nice to add some usage examples for the new utilities

2024-10-30 08:52 UTC, novusnota commented on src/interpreter.ts
> +            .on({ kind: "id" })((ast) => this.interpretName(ast))
Cool, but doesn't this create a ton of small `{ kind: whatever }` objects each time `interpretExpression()` is called?

2024-10-30 13:34 UTC, anton-trunov commented
Perhaps let's try applying it to the map key/value pair types once #993 is merged

2024-11-05 09:53 UTC, verytactical commented on src/interpreter.ts
> +            .on({ kind: "id" })((ast) => this.interpretName(ast))
Indeed it does, but there's not much we can do about it.

2024-11-06 08:51 UTC, anton-trunov requested changes
Let's revert changes on `switch` which are not strictly necessary and keep them only for pairs of key/value types where exhaustivity is desired

2024-11-06 08:51 UTC, anton-trunov commented on src/interpreter.ts
> +    public interpretExpression = (ast: AstExpression): Value =>
I think this change is not strictly necessary, since a missing case in this `switch` should be caught by ESLint.

2024-11-06 08:51 UTC, anton-trunov commented on src/generator/writers/writeStdlib.ts
> +        return match(key)
I would say this change is not strictly necessary, ESLint would catch it.

2024-11-06 08:52 UTC, anton-trunov commented
CI is not all green

2024-11-11 18:27 UTC, anton-trunov approved these changes

2024-11-11 18:28 UTC, merged